export const BEDISPATCH = "BEDISPATCH";
export const BEDISPATCH_ERROR = "BEDISPATCH_ERROR";

export const MOVIE_DETAILS = "MOVIE_DETAILS";
export const MOVIE_DETAILS_ERROR = "MOVIE_DETAILS_ERROR";

export const CAST_DETAILS = "CAST_DETAILS";
export const CAST_DETAILS_ERROR = "CAST_DETAILS_ERROR";
